# Generated by Django 5.2.7 on 2025-10-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description du produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Image (URL)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (€)'),
        ),
    ]
